### ISSUE TITLE
Suddenly “this.audiocontext.createScriptProcessor is not a function” error in p5js-sound

### ISSUE THREAD

**Issue by artponomariov** [processing/p5.js-sound#154]
I have a website, that should play mp3 file after clicking on a logo. Problem is with this [line](https://github.com/processing/p5.js/blob/master/lib/addons/p5.sound.js#L2208). Without any reason after two years of proper work it started to give this error. 

> Uncaught TypeError: this.audiocontext.createScriptProcessor is not a function.

I found out that it works in firefox and on some computers with older versions of chrome. How to solve this problem?

**Comment by therewasaguy** [comment]
Hmm, the [Script Processor](https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode) has been on its way to deprecation for 2+ years. I was actually kind of excited to see this issue because I thought it meant that its long awaited and more efficient replacement, the AudioWorklet, was now available. Unfortunately, the AudioWorklet, as far as I can find, is still not available in any browsers yet. The ScriptProcessor should continue to work in the meantime.

Can you share a link to your project? 

What version of Chrome? I just checked in latest versions of Chrome 55.0.2883.95, Canary 57.0.2960.0 and Chromium 57.0.2961.0 and createScriptProcessor, and p5 scripts that rely on it, are working.

What version of p5.sound.js? If it's two years old, there could be some other browser incompatibility issues that would be resolved by updating to a newer version.

**Comment by StupidUserSmartAnswer** [comment]
http://bassfunk.moscow/ link to the project, It was working with the version 54.0.2840.71 m , after I updated to Version 55.0.2883.87 m  it stopped working

**Comment by therewasaguy** [comment]
Thanks for the link. I'm also seeing this error on your site. It's running a version of p5.sound from 2015, and the issue is fixed if you update to a newer version of p5.sound, for example from [here](https://cdnjs.com/libraries/p5.js/).

It seems to be related to https://github.com/processing/p5.js-sound/issues/148. In Chrome, `AudioContext.prototype.hasOwnProperty('createScriptProcessor');` now returns `false` and it looks like in p5.sound v0.2.0 2015-05-30 it would have been getting overridden by a patch that was meant to fix conflicts between different implementations of the Web Audio API.

**Comment by therewasaguy** [comment]
i'll leave this open as you're probably not the only one who'll run into this issue

**Comment by StupidUserSmartAnswer** [comment]
thanks for your help.

**Comment by df6000** [comment]
I'm also getting this error on Chrome, with the 11/01/2016 version of p5.sound.

**Comment by df6000** [comment]
ps that's on Chrome  56.0.2924.87, amd the page that is generating the errors, www.thisisnotlaselva.net, is playing html5 audio normally

**Comment by therewasaguy** [comment]
@df6000 Hmm, this issue is fixed in the 11/01/2016 version of p5.sound, and I'm not seeing the error when I visit your site with Chrome 56.

I am seeing a different error when I click the mouse. It seems that `preload` is not finishing so `setup` is not being called. I believe if you remove the `loaded` callback from `loadSound` it will work. (preload works with asynchronous functions because it adds setup as the callback once everything has loaded, so if you provide your own callback it gets tripped up). If that doesn't solve the issue, feel free to create a new issue. I'd really like to experience This is not La Selva!

**Comment by df6000** [comment]
Hey thanks for the answer!  I embarrassingly didn't notice your response until this week, finally had a chance to check it out, and you're absolutely right!  I had several errors in the code which I fixed....there are still a few glitchy things and some general interface stuff that I need to fix/rework but it's more or less working again!  thank you!

**Comment by montoyamoraga** [comment]
because of the comments on this thread, i understand the issue was fixed, so i am closing it for now ~
